# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import visualizer_pb2 as visualizer__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in visualizer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeneratorServiceStub:
    """Service definition for generator-to-visualizer communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamFrames = channel.stream_stream(
                '/visualizer.GeneratorService/StreamFrames',
                request_serializer=visualizer__pb2.FrameRequest.SerializeToString,
                response_deserializer=visualizer__pb2.FrameResponse.FromString,
                _registered_method=True)
        self.GetFrameInfo = channel.unary_unary(
                '/visualizer.GeneratorService/GetFrameInfo',
                request_serializer=visualizer__pb2.GetFrameInfoRequest.SerializeToString,
                response_deserializer=visualizer__pb2.GetFrameInfoResponse.FromString,
                _registered_method=True)
        self.GetGeneratorStatus = channel.unary_unary(
                '/visualizer.GeneratorService/GetGeneratorStatus',
                request_serializer=visualizer__pb2.GetGeneratorStatusRequest.SerializeToString,
                response_deserializer=visualizer__pb2.GetGeneratorStatusResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/visualizer.GeneratorService/HealthCheck',
                request_serializer=visualizer__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=visualizer__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetCacheStatus = channel.unary_unary(
                '/visualizer.GeneratorService/GetCacheStatus',
                request_serializer=visualizer__pb2.CacheStatusRequest.SerializeToString,
                response_deserializer=visualizer__pb2.CacheStatusResponse.FromString,
                _registered_method=True)


class GeneratorServiceServicer:
    """Service definition for generator-to-visualizer communication
    """

    def StreamFrames(self, request_iterator, context):
        """Bidirectional streaming pipeline for on-demand frames and flow control.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFrameInfo(self, request, context):
        """Metadata endpoints retained for auxiliary UI features.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGeneratorStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health monitoring endpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCacheStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeneratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamFrames': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=visualizer__pb2.FrameRequest.FromString,
                    response_serializer=visualizer__pb2.FrameResponse.SerializeToString,
            ),
            'GetFrameInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFrameInfo,
                    request_deserializer=visualizer__pb2.GetFrameInfoRequest.FromString,
                    response_serializer=visualizer__pb2.GetFrameInfoResponse.SerializeToString,
            ),
            'GetGeneratorStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGeneratorStatus,
                    request_deserializer=visualizer__pb2.GetGeneratorStatusRequest.FromString,
                    response_serializer=visualizer__pb2.GetGeneratorStatusResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=visualizer__pb2.HealthCheckRequest.FromString,
                    response_serializer=visualizer__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetCacheStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCacheStatus,
                    request_deserializer=visualizer__pb2.CacheStatusRequest.FromString,
                    response_serializer=visualizer__pb2.CacheStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'visualizer.GeneratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('visualizer.GeneratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeneratorService:
    """Service definition for generator-to-visualizer communication
    """

    @staticmethod
    def StreamFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/visualizer.GeneratorService/StreamFrames',
            visualizer__pb2.FrameRequest.SerializeToString,
            visualizer__pb2.FrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFrameInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualizer.GeneratorService/GetFrameInfo',
            visualizer__pb2.GetFrameInfoRequest.SerializeToString,
            visualizer__pb2.GetFrameInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGeneratorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualizer.GeneratorService/GetGeneratorStatus',
            visualizer__pb2.GetGeneratorStatusRequest.SerializeToString,
            visualizer__pb2.GetGeneratorStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualizer.GeneratorService/HealthCheck',
            visualizer__pb2.HealthCheckRequest.SerializeToString,
            visualizer__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCacheStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualizer.GeneratorService/GetCacheStatus',
            visualizer__pb2.CacheStatusRequest.SerializeToString,
            visualizer__pb2.CacheStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FrameFileServiceStub:
    """Service for serving pregenerated HDF5 frames from disk (remote_hdf5 mode)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFileServerMetadata = channel.unary_unary(
                '/visualizer.FrameFileService/GetFileServerMetadata',
                request_serializer=visualizer__pb2.FileServerMetadataRequest.SerializeToString,
                response_deserializer=visualizer__pb2.FileServerMetadataResponse.FromString,
                _registered_method=True)
        self.ListAvailableFrames = channel.unary_unary(
                '/visualizer.FrameFileService/ListAvailableFrames',
                request_serializer=visualizer__pb2.ListFramesRequest.SerializeToString,
                response_deserializer=visualizer__pb2.ListFramesResponse.FromString,
                _registered_method=True)
        self.GetPreGeneratedFrame = channel.unary_unary(
                '/visualizer.FrameFileService/GetPreGeneratedFrame',
                request_serializer=visualizer__pb2.PreGeneratedFrameRequest.SerializeToString,
                response_deserializer=visualizer__pb2.PreGeneratedFrameResponse.FromString,
                _registered_method=True)


class FrameFileServiceServicer:
    """Service for serving pregenerated HDF5 frames from disk (remote_hdf5 mode)
    """

    def GetFileServerMetadata(self, request, context):
        """Get metadata about the available frames
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAvailableFrames(self, request, context):
        """List all available frame indices
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPreGeneratedFrame(self, request, context):
        """Get a single pre-generated frame by index
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrameFileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFileServerMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileServerMetadata,
                    request_deserializer=visualizer__pb2.FileServerMetadataRequest.FromString,
                    response_serializer=visualizer__pb2.FileServerMetadataResponse.SerializeToString,
            ),
            'ListAvailableFrames': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAvailableFrames,
                    request_deserializer=visualizer__pb2.ListFramesRequest.FromString,
                    response_serializer=visualizer__pb2.ListFramesResponse.SerializeToString,
            ),
            'GetPreGeneratedFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPreGeneratedFrame,
                    request_deserializer=visualizer__pb2.PreGeneratedFrameRequest.FromString,
                    response_serializer=visualizer__pb2.PreGeneratedFrameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'visualizer.FrameFileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('visualizer.FrameFileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrameFileService:
    """Service for serving pregenerated HDF5 frames from disk (remote_hdf5 mode)
    """

    @staticmethod
    def GetFileServerMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualizer.FrameFileService/GetFileServerMetadata',
            visualizer__pb2.FileServerMetadataRequest.SerializeToString,
            visualizer__pb2.FileServerMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAvailableFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualizer.FrameFileService/ListAvailableFrames',
            visualizer__pb2.ListFramesRequest.SerializeToString,
            visualizer__pb2.ListFramesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPreGeneratedFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualizer.FrameFileService/GetPreGeneratedFrame',
            visualizer__pb2.PreGeneratedFrameRequest.SerializeToString,
            visualizer__pb2.PreGeneratedFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
